### DISCUSSION TITLE
Has anyone tried Lilygo T-POE Pro?

### DISCUSSION THREAD

**Discussion by Imanol82** [Sleeper85/esphome-jk-bms-can#70] [Ideas]
Hello.

Has anyone tested this project on the Lilygo T-POE Pro?

This is a esp32 + Rs485 + can + poe + isolated... All in one!!

![image](https://github.com/user-attachments/assets/62b9e21a-b7ea-4a4a-bf93-e3dc6c5bd720)

https://www.lilygo.cc/products/t-poe-pro

It's a perfect solution for this project. Don't you think?

This is from ChatGPT:

```
esphome:
name: tpoe_pro
platform: ESP32
board: esp32-poe-iso # Board similar that supports Ethernet and PoE

Ethernet Configuration
ethernet:
type: LAN8720
mdc_pin: GPIO23 # MDC Pin
mdio_pin: GPIO18 # MDIO Pin
clk_mode: GPIO17_OUT # Clock Pin
power_pin: GPIO12 # Ethernet Power Pin
phy_addr: 0 # PHY Address

RS485 Configuration
uart:
id: uart_rs485
tx_pin: GPIO4 # TX Pin for RS485
rx_pin: GPIO16 # RX Pin for RS485
baud_rate: 9600
parity: NONE
stop_bits: 1

rs485:
id: rs485_hub
uart_id: uart_rs485
control_pin: GPIO21 # Control Pin for RS485 transceiver

CAN bus Configuration
canbus:
id: can_hub
tx_pin: GPIO22 # TX Pin for CAN
rx_pin: GPIO19 # RX Pin for CAN
bit_rate: 500kbps

Logger, API, and OTA Configuration
logger:
api:
ota:
```

Thanks!!

**Comment by Imanol82** [comment]
I have bought one to try. :)

**Comment by Imanol82** [comment]
I have made a stupid mistake. This board don't have Can Bus...

**Reply by Sleeper85** [reply]
Yes I looked yesterday but I didn't find a CAN transceiver either :face_with_diagonal_mouth:

**Comment by Imanol82** [comment]
My mistake. I don't know why I see it.

Lilygo T-CAN485 this one yes have both, but only is wifi not Ethernet poe. 

But maybe is a good esp to try

https://www.lilygo.cc/products/t-can485


Thanks!!

**Comment by cinusik** [comment]
This will be better choice:
[https://www.lilygo.cc/products/t-connect](https://www.lilygo.cc/products/t-connect)
ESP32-S3 and 3xRS485 and 1xCAN - all isolated.
Perfect board for this project.
Or like me if you like displays than lot more expensive will be M5Stack CoreS3 with can, rs485 and poe ETH modules.

**Comment by Imanol82** [comment]
The thing is that I would like some more AIO solution. In the inverter, for example, I also had an ESP32, I changed it with a Modbus TCP and well, it's amazing... It always works, you never have to update it, it's very stable...

![image](https://github.com/user-attachments/assets/6ad5a153-8bbc-4ed0-aff3-e2928181855d)


Thanks @cinusik, I'll take a look

I will continue investigating... Thank you!!

**Comment by Sleeper85** [comment]
@Imanol82 

What kind of BMS do you have?

**Reply by Imanol82** [reply]
Those ones. JK pb

![IMG_20240625_193022](https://github.com/user-attachments/assets/10b8b9a5-1588-42ec-8301-a9e2bbca5f6c)

The problem is that wifi signal is not very well inside the metal closed. That's why I'm looking for a eth poe solution

**Comment by Imanol82** [comment]
In the end, maybe I'll try a Modbus-tcp like the one I used for the inverter. I don't know if I'll be able to read the BMS... I'll have to try it.

Now I have them with an esp32 and Txubelaxu's project. But I also would like to try YamBMS. I guess like everyone here, we are changing always...


Thank you for your work and support!!!

**Comment by Sleeper85** [comment]
With the JK-PB, I like this solution with Atom S3 and RS485. You can keep the Atom S3 outside the metal box and even glued to your inverter, the RS485 bus can be 1200m.

![Xenon](https://github.com/user-attachments/assets/37b65cb8-ab62-438e-ace0-feb0c25f28a1)

![Xenon2](https://github.com/user-attachments/assets/bebfe4bf-f364-4f0c-ab32-8270992d281d)

**Comment by Imanol82** [comment]
My plan is to try to do something with this, I don't know if I can... but I'll have to try :)

![image](https://github.com/user-attachments/assets/53b41929-07fa-4447-86fa-f194ac4323c9)

 or

![image](https://github.com/user-attachments/assets/ab89fc1e-ab6c-45dc-bd53-056d3becf313)

**Reply by Sleeper85** [reply]
OK, good luck 😉

**Reply by Imanol82** [reply]
I'm afraid I'll need more than good luck...

**Reply by Sleeper85** [reply]
The default CAN protocol of the Deye is PYLON 1.2 so very simple.
You have to send it the name PYLON to see the SOH value.

**Reply by Imanol82** [reply]
Thanks! First step is to read the BMSs... :)

**Comment by Imanol82** [comment]
In the end I'm going to try it with the ESP32 ETH01-EVO. 
It's POE and it seems that it is already integrated into ESPHome.

![image](https://github.com/user-attachments/assets/dec22082-eb2b-45f3-80a0-9da412964c7c)

I know that the RS485 board is not the isolated model, it is what I have at home and I have not received the other one yet...
I'll have to try it :)

**Comment by Sleeper85** [comment]
[ESP32-S3-Touch-LCD-7](https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-7) with integrated RS485 and CAN board (non-isolated).

![image](https://github.com/user-attachments/assets/79ddd1e0-d3b1-4d59-9400-63f03419e77c)

![image](https://github.com/user-attachments/assets/8b221705-6d0d-4547-8f1a-13b1089a5e31)

**Reply by MrPabloUK** [reply]
I intend to order one of these boards for testing on my side.
I may be moving to a multi battery setup with the JK-PB BMS

**Reply by Imanol82** [reply]
+ ETH Poe will be perfect hehe. With a beautiful screen

**Comment by Imanol82** [comment]
Hello!

First step, DONE! 
ETH01-EVO POE is working!

![image](https://github.com/user-attachments/assets/32d5572b-c970-47a2-b5c3-c1134d0129d2)

Second step, tray to use YamBMS with this esp32.
Lets play ;)

![image](https://github.com/user-attachments/assets/e87ad4ac-54a8-42c2-8ba1-d53e66a75088)

**Comment by Imanol82** [comment]
I try but it's really difficult... The board is very different.

I try to create "packages/board/board_esp32-c3-devkitm-1_ETH01-EVO.yaml" but there are a lot of errors with the wifi and more topics.

- No Wifi. (if you use ETH, can't use wifi)
- I don't know where to define pins:

![image](https://github.com/user-attachments/assets/b8a60a21-fb1f-43cf-bbb4-4768eaa60012)


- Is mandatory to put this code because it's not integrated in ESPHome jet:

```
ethernet:
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 20MHz
```

If anyone who knows wants to help me, I would be happy to be a beta tester.
I think this board is very interesting for this project.

Thank you very much!

**Comment by Sleeper85** [comment]
@Imanol82 

I'll see if I can create a board with the schematic you provided.

**Reply by Imanol82** [reply]
Wow!!!!! It'll be amazing!!!!!

Thank you very much!

**Reply by Sleeper85** [reply]
I made 3 new YAML for ETH01-EVO but...

`DM9051` is not a valid option for ethernet ?

```YAML
Failed config

ethernet: [source packages/board/board_esp32-c3-eth01-evo.yaml:45]
  
  Unknown value 'DM9051', valid options are 'LAN8720', 'RTL8201', 'DP83848', 'IP101', 'JL1101', 'KSZ8081', 'KSZ8081RNA', 'W5500'.
  type: DM9051
  clk_pin: GPIO07
  mosi_pin: GPIO10
  miso_pin: GPIO03
  cs_pin: GPIO09
  interrupt_pin: GPIO08
  reset_pin: GPIO06
  clock_speed: 20MHz
```

**Reply by Imanol82** [reply]
Hi!

I Forgot, this is neccesary too: (this is because this DM9051 is not conpatible yet. they're working on it)

```
esp32:
  board: esp32-c3-devkitm-1
# currently needed, but not in the future
  variant: esp32c3
  framework:
    type: esp-idf
    version: latest
    platform_version: 6.5.0

external_components:
  - source: github://pr#6861
    components:
      - ethernet
```

The external component.

Thank you very much!!

**Comment by Sleeper85** [comment]
I managed to compile at home with this `W5500`, it's up to you to test with `DM9051`.

I'm not publishing to the git repository because it's a really special setup, I had to modify/create several YAMLs.

All GPIOs and hardware is configured in: **packages/board/board_esp32-c3-eth01-evo.yaml**

```YAML
ethernet:
  type: W5500
  clk_pin: 7
  mosi_pin: 10
  miso_pin: 3
  cs_pin: 9
  interrupt_pin: 8
  reset_pin: 6
  clock_speed: 20MHz
```

[YamBMS_1.4.4.B_ETH01-EVO_Imanol82.zip](https://github.com/user-attachments/files/16899965/YamBMS_1.4.4.B_ETH01-EVO_Imanol82.zip)

**Reply by Imanol82** [reply]
wow, thank you very much. 

Tomorrow I'll test. I'll inform you if it works well. I think this is very interesting esp32 :)

**Reply by Imanol82** [reply]
I couldn't wait... I already have everything installed.

Everything is waiting for tomorrow to connect the 2 RJ45 cables :)
![image](https://github.com/user-attachments/assets/f06a7fbf-34d5-4a9d-9b76-f73a17c53993)



Thank you very much for your incredible work.

**Comment by Imanol82** [comment]
Sorry for the late answer. 

I'm trying only the RS485 part. My idea is to keep only this because I only need to read (something like Txubelaxu project)
But I only get this:

```
INFO Starting log output from 192.168.31.114 using esphome API
INFO Successfully connected to yambms @ 192.168.31.114 in 0.002s
INFO Successful handshake with yambms @ 192.168.31.114 in 0.059s
[23:11:27][W][esp-idf:000]: I (508302) tsens: Config range [-10°C ~ 80°C], error < 1°C

[23:11:37][W][esp-idf:000]: I (518300) tsens: Config range [-10°C ~ 80°C], error < 1°C

[23:11:47][W][esp-idf:000]: I (528301) tsens: Config range [-10°C ~ 80°C], error < 1°C

```

Any idea? thank you very much!!!

**Reply by Sleeper85** [reply]
> Sorry for the late answer.
> 
> I'm trying only the RS485 part. My idea is to keep only this because I only need to read (something like Txubelaxu project) But I only get this:
> 
> ```
> INFO Starting log output from 192.168.31.114 using esphome API
> INFO Successfully connected to yambms @ 192.168.31.114 in 0.002s
> INFO Successful handshake with yambms @ 192.168.31.114 in 0.059s
> [23:11:27][W][esp-idf:000]: I (508302) tsens: Config range [-10°C ~ 80°C], error < 1°C
> 
> [23:11:37][W][esp-idf:000]: I (518300) tsens: Config range [-10°C ~ 80°C], error < 1°C
> 
> [23:11:47][W][esp-idf:000]: I (528301) tsens: Config range [-10°C ~ 80°C], error < 1°C
> ```
> 
> Any idea? thank you very much!!!

It's normal with logger to WARN level.

**Reply by Imanol82** [reply]
But I only receive that information, nothing more haha, I think I have made something wrong...

**Reply by Sleeper85** [reply]
This logs is normal with logger level to WARN.

**Reply by Imanol82** [reply]
I thought it was wrong and I spent days reinstalling everything in different ways hahahaha

Likewise, nothing works, it's like everything is disconnected. Any ideas or tests I can do?


Thank you!!

**Comment by Imanol82** [comment]
I tried again with file you sent me, a clean installation. No change names, no change nothing.
- Put packages folder on \\192.168.31.110\config\esphome\
- I've compiled and installed all the program, the only change is that I put manual IP con board_esp32-c3-eth01-evo.yaml
```
substitutions:
  board_chip: "ESP32-C3"
  board_name: "ETH01-EVO"

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf
    version: latest
    platform_version: 6.5.0

external_components:
  - source: github://pr#6861
    components:
      - ethernet

ethernet:
  type: DM9051 # W5500
  clk_pin: 7
  mosi_pin: 10
  miso_pin: 3
  cs_pin: 9
  interrupt_pin: 8
  reset_pin: 6
  clock_speed: 20MHz
  manual_ip:
    static_ip: 192.168.31.114 
    gateway: 192.168.31.1
    subnet: 255.255.255.0
    dns1: 192.168.31.1 
```
- Everything looks installed OK,
- I've restarted the inverter and BMSs just in case, BMS01 is dip 1, BMS 02 is dip 2.

The result is nothing:

![image](https://github.com/user-attachments/assets/9247d0ff-9e92-4665-b25c-983ce5b20218)


![image](https://github.com/user-attachments/assets/16c11756-512c-44ad-91e1-5df4f6460231)

![image](https://github.com/user-attachments/assets/d8fb9a57-da78-4ee7-96b4-03ab117d9dda)


Thank you very much for your support!!
