### DISCUSSION TITLE
Any questions ?

### DISCUSSION THREAD

**Discussion by Sleeper85** [Sleeper85/esphome-jk-bms-can#71] [General]
@solarfocus

Hi,

If you have any questions, you can ask them here.

**Comment by cinusik** [comment]
Do you implement multiple shunt solution over RS485 in 1.4.4? Just asking.  Not need that functionality right now but it will be nice to have it for the future ideas ;)
FYI: BMS Calibration was the solution for BMS SOC differences. Just to let you know that 10 Amps calibration was not enoug - I went for calibration at 30Amps and now both BMSes are spot on with SOC.

**Reply by Sleeper85** [reply]
Yes multi-shunt will be part of 1.4.4, it already works for me.

**Reply by solarfocus** [reply]
Great ,well I bought me that can bus isolation from m5 ,have some esp 32 on hand and like to set up a close loop connection with a JK BMS to my 6kw deye EU inverter and a diy 48v Battery (Eve mb31),
The issue I see is that I installed the whole system /solar but when it comes to computer/esp /etc.-
I am lost,for that I need help,

**Comment by Sleeper85** [comment]
@solarfocus 

To help you you have to be more specific.

- Inverter: Deye = OK
- A 16S EVE MB31 battery = OK
- JK-BMS ? How many ? Which JK-B or JK-PB model ?
- M5stack CAN bus board, which one? SKU number ?
- ESP32 board, which model ?

**Comment by solarfocus** [comment]
1 BMS 150 A
Cais3050G
Esp 32 dev kit v1
________________________________

**Reply by Sleeper85** [reply]
> Cais3050G

[You talk about this CAN unit ?](https://docs.m5stack.com/en/unit/can)

You have a BMS but I still don't know which model ?
The old JK-B model or the new JK-PB ?

**Comment by solarfocus** [comment]
I was trying to send you a photo,
Yes it is the old one BMS ,
Yes this can unit ,

So the question is:
Do I need to download all the esp home files ?
I read something like yml ,

If possible a clear guide what I need to download would help ,
Also what cables I need to connect?

Appreciate your time and effort to help,

Andy
________________________________

**Reply by Sleeper85** [reply]
[YamBMS 1.4.4](https://github.com/Sleeper85/esphome-jk-bms-can/tree/development)

1) Download all files.

![image](https://github.com/user-attachments/assets/726422a1-4f3b-4abb-976e-821fe4d67e21)

2) To compile you need what I have highlighted in pink

![image](https://github.com/user-attachments/assets/fb5b4d55-219f-464a-962e-607139cafe24)

3) The default GPIOs you should use

```YAML
uart:
  # UART 1
  - id: uart_esp_1
    tx_pin: 17 # to BMS RX
    rx_pin: 16 # to BMS TX
    baud_rate: 115200

canbus:
  # CANBUS NODE 1
  - platform: esp32_can
    id: canbus_node1
    tx_pin: 23 # to CAN board CTX
    rx_pin: 22 # to CAN board CRX (with 4.7K resistor except for SN65HVD230)
    can_id: 1
    bit_rate: 500kbps
```

[See the documentation.](https://github.com/Sleeper85/esphome-jk-bms-can/tree/development?tab=readme-ov-file#contents)
[See the schematic.](https://github.com/Sleeper85/esphome-jk-bms-can/blob/development/documents/README/BMS_JK-B_UART_solution.md#generic-esp32-devkit-v1-30-pin)
