### ISSUE TITLE
some improvements

### ISSUE THREAD

**Issue by octane321** [Sleeper85/esphome-jk-bms-can#12]
works great so far - i have some improvements requests

- Use BMS max charge/discharge current (-5%) [tested and working]
- recover globals (charge/float voltage, absorbtion time etc) after restart (or is there any disadvantage like wearing?) [tested and working]
- add ability to change CAN Protokoll and Name dynamic (for testing inverter communication)
- use celltemperatures in a relevant way (if temp <20°C, use min temp of cells, if >20 and <40°C use average temp, if >40°C use max temp)
- seperate charge logic into new .yaml and include it as a package

what are your thoughts about that?

THX

**Comment by Sleeper85** [comment]
Hi,

There are some interesting points like that of temperature, I'm about to add an "Alarms Logic" section see the links below.

I have a lot of requests for improvement and some will not suit everyone.
I think I should collect all the requests and hold a vote for each question.

I note your requests.

**Comment by virus100b** [comment]
Hello,

@ Sleeper85 Congratulation for the nice project you have done 
I have moddifed liitle your code adding the option of modifying discharge current from slider. I am also planning to implement limiting discharging current to 10% from normal discharging current when battery cappacity drop below 15%. I know some BMS has this function. 

What is you oppinion about this?

**Comment by Sleeper85** [comment]
I have already added an "Alarms Logic" section to address the [@arzaman](https://diysolarforum.com/members/69458/) and [@hxx](https://diysolarforum.com/members/21118/) balancing problem. I'm going to add temperature control to it. Thus, this section will aim to detect problems before the BMS cut-off which will prevent it from working its MOSFETs to cut a lot of amps.

Here's what will be part of version 1.16.5 :

- High temperature control (45°C) => stop charging and discharging
- Low temperature control (0°C) => stop charging
- Cell max voltage control (Bulk V. / 16) => reduce the charging amps to 5A and start a balancing phase
- Cell min voltage control (min_discharge_v /16) ? or bms_cell_undervoltage_protection + 0.x ? => stop discharging

This could be based on information from the BMS or values in the script.
If the BMS is poorly programmed then it will not be useful.

I can take advantage of this to add some of your requests such as the temperature sent (min or max) or a new slider for the discharge current.

But some of your requests are special and may not suit everyone.

FYI: I'm preparing for a long 4 month trip, version 1.16.5 will be the last one I can test before leaving.

**Comment by octane321** [comment]
Didnt read all about the problems from arzaman and hxx but coult imagine what problems they have and the solution sounds good.
I would appreciate if the new Alarm logic will be based on the bms values - a poorly configured BMS is always a problem, but if you want to implement some values to set it would be not a bad idea.

i also understand if some requests will not suite to everyone - i´ll try to implement them for personal needs then if i´m able to.
Looking forward to 1.16.5 ;-)

I wish you a wonderful time on the trip

**Comment by virus100b** [comment]
High temperature control (45°C) => stop charging and discharging, i believe is temperature of the cells measured by the two external probes, as the mosfets are not "suffering" by working at 45°C.
Regarding my plan with 10% of the current  limit function i can understand that it my not be suitable for others and i can tweak my code for that. For now i will wait for your final reales as the new feature are nice to have.

Some question:
1. Why did you name the MOS temperature "tube temperature"? Was a bit confusing at the begining as inside BMS they are called MOS.
2.   Discharging low temperature and Discharging low temperature recovery i cannot find in my BMS settings thus are present in the ESP home. This temperature may be hidden?

![Discharging Temp](https://github.com/Sleeper85/esphome-jk-bms-can/assets/64686560/c01737fd-6d9b-4a4f-9da5-5f9580d5a2e0)

P.S. The inverter i have is a  Deye sun 12k-sg04lp3-eu. I have seen that is already in the confirmed working inverters, but i can reconfirms that is working fine ESP32 and TJA1050. 

For power the ESP i have use 12V that inverter provide on CN2 pins 7, 8 and a stepdown converter. Maybe for Deye owners my be useful info spare using a 48-5V Power supply.

**Comment by octane321** [comment]
@virus100b Good point on the High temperature control
the 45°C should be triggered by the cell votages (external probes)
But there is also a MOS OTP and OTPR which could also trigger an alarm.
Would be great to limit the current by x% in both cases instead of shutting (dis)charging completely down

But i don´t get the point of limiting the current if SoC<15%
This will only push the inverter in a range where the efficiency is really bad due to the constant selfcomsumption. And it does not harm the cells or BMS to discharge at the normal rate - so why would you do that?


> 1. Why did you name the MOS temperature "tube temperature"? Was a bit confusing at the begining as inside BMS they are called MOS.

The transistors which control the charging and discharging function of the BMS are commonly called "MOS Tubes"

> 2\. Discharging low temperature and Discharging low temperature recovery i cannot find in my BMS settings thus are present in the ESP home. This temperature may be hidden?

these settings are only available on the JK Inverter BMS i think - but i might be wrong...there are so many different Hardware and Software Versions out there

**Comment by Sleeper85** [comment]
@octane321 The temperature sent with ID 0x356 has an informative role. There are other parts in the code where the minimum or maximum temperature is communicated or used. So I opted to simply send the average temperature.

@virus100b I added the "Discharging current max" slider.

Compiled at home but haven't had time to do all the tests yet.

V1.16.5 Sleeper85 : Add Preventive Alarms Logic with Balancing function, CAN ID 0x356: send average temperature of T1/T2, new "Discharging current max" slider

```YAML
# +--------------------------------------+
# | Preventive Alarms Logic              |
# +--------------------------------------+
# Balancing max current, the charging current will be reduced to this value as soon as the voltage of a cell reaches 3.45v (bulk_voltage / 16)
  balancing_a: "5"
# +--------------------------------------+
# Information from the EVE LF280K v2 cell datasheet
# LFP Recommended Operating Temperature Range : 10~45°C
# Number of cycles at 25°C : 6000
# Number of cycles at 45°C : 2500
# 60°C  : Never charging or discharging
# 0°C   : Never charging
# -30°C : Never discharging
# +--------------------------------------+
# High Temp Protection - Temp > OTP : Stop Charging and Discharging
  otp: "45.0"
# Low Temp Protection  - Temp < UTP : Stop Charging
  utp: "1.0"
```

[JK-BMS-CAN 1.16.5](https://github.com/Sleeper85/esphome-jk-bms-can/files/14173400/jk-bms-can_1.16.5.zip)
