### ISSUE TITLE
Naming issues for sensors - Duplicate device name / hostname

### ISSUE THREAD

**Issue by luckylinux** [Sleeper85/esphome-jk-bms-can#38]
I previously mentioned this issue regarding Battery 02, when upgrading from Syssi esphome-jk-bms to Sleeper85 esphome-jk-bms-can.

I now flashed also Battery 01 in order to have more consistent readings across the different batteries.

The essential problem is that the hostname is repeated in the sensor.xxx access string.

But it's not always the case. Some are, some are not.

I deleted the previous MQTT Device (ESP32 board) after reflashing this one (Atom S3 Lite Board).

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/db1cb329-a134-4d1f-b49d-c8cfd53dab94)

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_power
      - entity: sensor.jk_bms_bat02_power
    title: Power
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat02_jk_bms_bat02_requested_charge_current
      - entity: sensor.jk_bms_bat02_jk_bms_bat02_requested_charge_voltage
      - entity: sensor.jk_bms_bat02_jk_bms_bat02_requested_discharge_current
    title: Requested Charge Parameters
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_current
      - entity: sensor.jk_bms_bat02_current
    title: Current
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_state_of_charge
      - entity: sensor.jk_bms_bat02_state_of_charge
    title: State of Charge
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_max_cell_voltage
      - entity: sensor.jk_bms_bat02_max_cell_voltage
    title: Maximum Cell Voltage
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_min_cell_voltage
      - entity: sensor.jk_bms_bat02_min_cell_voltage
    title: Minimum Cell Voltage
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_delta_cell_voltage
      - entity: sensor.jk_bms_bat02_delta_cell_voltage
    title: Cell Delta Voltage
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_temperature_sensor_1
      - entity: sensor.jk_bms_bat01_temperature_sensor_2
      - entity: sensor.jk_bms_bat02_temperature_sensor_1
      - entity: sensor.jk_bms_bat02_temperature_sensor_2
    title: Ambient Temperature

```

YAML file used with Syssi esphome-jk-bms: https://github.com/luckylinux/jk-bms-build-helpers/blob/main/_old/esphome-jk-bms/esp32-ble-2.0.0.yaml
YAML file used with Sleeper85 esphome-jk-bms-can: https://github.com/luckylinux/jk-bms-build-helpers/blob/main/esphome-jk-bms-can/esp32-ble-1.17.5.yaml

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/38846930-1d47-40a7-a074-867d47355dcc)
![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/84e0e5ed-c190-43a4-b58c-3cee84a89a66)

For reference (since I didn't have screenshots from before apart from those on the DIYSolarForum - will try to include those if I can find them), my weather Station Sainlogic WS3500 via Weewx and using weewx-mqtt reports like this to the Mosquitto MQTT Server:
![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/c8ee020e-282c-4a64-9da7-13b79e990df3)

**Comment by luckylinux** [comment]
I couldn't find screenshots for Battery 02 having that issue before ...

Maybe related to https://community.home-assistant.io/t/esphome-mqtt-devices-have-duplicated-names/609858/4 ?

**Comment by luckylinux** [comment]
What's worse is that it's not consistent and even in MQTT it shows one thing, in home assistant another.

I updated the simplified view for now this works, but it's definitively a hack:

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/e37292e8-bb6b-4d28-bef9-0ca66f6ded3d)

```
type: vertical-stack
cards:
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_power
      - entity: sensor.jk_bms_bat02_power
    title: Power
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat02_jk_bms_bat02_requested_charge_current
      - entity: sensor.jk_bms_bat02_jk_bms_bat02_requested_charge_voltage
      - entity: sensor.jk_bms_bat02_jk_bms_bat02_requested_discharge_current
    title: Requested Charge Parameters
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_current
      - entity: sensor.jk_bms_bat02_current
    title: Current
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_state_of_charge
      - entity: sensor.jk_bms_bat02_state_of_charge
    title: State of Charge
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_max_cell_voltage
      - entity: sensor.jk_bms_bat02_max_cell_voltage
    title: Maximum Cell Voltage
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_min_cell_voltage
      - entity: sensor.jk_bms_bat02_min_cell_voltage
    title: Minimum Cell Voltage
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_delta_cell_voltage
      - entity: sensor.jk_bms_bat02_delta_cell_voltage
    title: Cell Delta Voltage
  - type: entities
    entities:
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_temperature_sensor_1
      - entity: sensor.jk_bms_bat01_jk_bms_bat01_temperature_sensor_2
      - entity: sensor.jk_bms_bat02_temperature_sensor_1
      - entity: sensor.jk_bms_bat02_temperature_sensor_2
    title: Ambient Temperature
```

![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/bbb4fbe3-1449-4ce4-bf80-7eae79fde1dc)
![image](https://github.com/Sleeper85/esphome-jk-bms-can/assets/7126291/be71f770-81db-4462-8b66-74dedcfdd9b1)

I tried:
- Restarted ESP32 of Battery01 (NEVER touch ESP32 of Battery02 / MASTER, otherwise grid goes down).
- Restarted Mosquitto MQTT Broker
- Restarted Home Assistant

That doesn't seem to help. There is something new going on here. Maybe a new library of ESPHome / IDF Framework is used compared to Syssi previous code ? Not sure.
